### PR TITLE
Allow VXI-11 SRQ channel to be omitted

### PR DESCRIPTION
**Pull request by norumwe12**
This change lets me use VXI-11 with a Keysight 53210A frequency counter.

### CODE REVIEW

**Comment by ralphlange** [comment]
Looks straightforward and compatible to me.

**Comment by MarkRivers** [comment]
Can you update RELEASE_NOTES.html and asynDriver.html?

**Comment by norumwe12** [comment]
Hmm…will check tomorrow….I thought that I had updated the documentation.  Will do release notes and send in the change.

**Comment by MarkRivers** [comment]
My mistake, you did update asynDriver.html, but not RELEASE_NOTES.html.

**Comment by norumwe12** [comment]
Which I tried to do — and I think that the folks that developed git did *everything* to make its use as obscure and complicated as possible.

I made the changes to the release notes, then:
wenorum@norume 320> git commit RELEASE_NOTES.html
<< add commit note in editor that pops up — save and quit >>
wenorum@norume 321> git push -u origin noSRQ
error: src refspec noSRQ does not match any.
error: failed to push some refs to 'https://github.com/epics-modules/asyn.git'


???
Can’t I add changes to a branch that I’m working on????

FWIW, here’s the new release notes:



> On Jan 26, 2017, at 4:54 PM, Mark Rivers <notifications@github.com> wrote:
> 
> My mistake, you did update asynDriver.html, but not RELEASE_NOTES.html.

-- 
Eric Norum
wenorum@lbl.gov

**Comment by MarkRivers** [comment]
Is the noSRQ branch the one you have checked out locally (use “git status” to see).

If so, then you can just do “git push”.   

git push -u origin noSRQ” is only needed when first setting up the tracking branch on Github, though I’m surprised that it fails.

You tried to put the release note in your message, but I don't see anything there.

**Comment by anjohnson** [comment]
Note that you can commit edits to text files directly on github. Make sure you're looking at the right branch, then while viewing the file click the pencil icon at the top right of the content.

**Pull request merged**
