### PR TITLE
Fix uninitialized member variable in devAsynXXXArray constructor

### LINKED ISSUE #193: devAsynXXXArray: uninitialized member crashes IOC when asyn port is not available
The constructor of `devAsynXXXArray` leaves the internal member variable `pInterface_` uninitialized if the ASYN port can't be found. (E.g., when the hardware is not available.)

The method `getIoIntInfo()` uses that variable and expects a `nullptr` if the initialization went wrong.

IOCs using the array support are arbitrarily crashing if the hardware is not available.
(Dereferencing uninitialized memory in `getIoIntInfo()`.)

### PR DESCRIPTION
**Pull request by ralphlange**
(fixes #193)

### CODE REVIEW

**Comment by ralphlange** [comment]
Do you want me to fix those configuration issues?

**Comment by MarkRivers** [comment]
That would be great!

**Comment by ralphlange** [comment]
Fixed on master with ceba8fe17ccb118c663e551674c8f4a0bd9c9169.

**Comment by ralphlange** [comment]
Rebased to asyn/master and force-pushed to trigger new CI builds.

**Pull request merged**
