### PR TITLE
Misc fixes found by static code analysis

### PR DESCRIPTION
**Pull request by ralphlange**
A set of fixes for different issues (few major, many minor) that were found by cppcheck/sonar at ITER.

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
@ralphlange this looks good thanks.  

My only comment is that changing %u to %lu for size_t arguments is still not correct on 64-bit Windows, right?  There a size_t is 64-bit but a long is 32-bit.  Changing is to *llu won't be correct on 32-bit machines since a size_t is 32-bit and a long long is 64-bit?  Should we cast the argument instead?

**Comment by norumwe12** [comment]
I presume this is an issue because there are platforms that don’t support the ‘z’ modifier for size_t  (“%zu”) nor the “PRI” string literals?
Perhaps some EPICS OS-dependent header could provide the PRIxxx literals for such machines?


> On Apr 29, 2023, at 8:06 AM, Mark Rivers ***@***.***> wrote:
> 
> My only comment is that changing %u to %lu for size_t arguments is still not correct on 64-bit Windows, right? There a size_t is 64-bit but a long is 32-bit. Changing is to *llu won't be correct on 32-bit machines since a size_t is 32-bit and a long long is 64-bit? Should we cast the argument instead?
> 
> 

— 
Eric Norum
***@***.***

**Comment by MarkRivers** [comment]
> I presume this is an issue because there are platforms that don’t support the ‘z’ modifier for size_t  (“%zu”) nor the “PRI” string literals?
Perhaps some EPICS OS-dependent header could provide the PRIxxx literals for such machines?

This has been discussed in this tech-talk thread.  Apparently of the supported architectures only vxWorks does not support %z.
https://epics.anl.gov/core-talk/2022/msg00321.php

**Comment by ralphlange** [comment]
True, I didn't consider that.
Guess the only waterproof option is to cast the argument to the widest in-the-wild type that we need to support. Anything else would either fail or be insufficient on some architectures. Only if that widest type is not supported by all compilers, we'd be in trouble.

**Comment by MarkRivers** [comment]
I thing cast to (long long) and %llu would work on all?

**Comment by ralphlange** [comment]
Worth a try.
Better than %z that would fail hard on VxWorks, while the other mismatches would just generate warnings.

**Pull request merged**
